name: Example

on:
  push:
    branches: 
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Displays a message
        run: echo "This changes are affecting the main branch"

      - name: Another task
        run: echo "Another Task"
        
